<?php
include 'connection.php';

// Get JSON data from the request
$jsonData = file_get_contents('php://input');
$data = json_decode($jsonData, true);

// Access individual data fields
$name = $data['name'];
$email = $data['email'];
$card = $data['card'];
$expiry = $data['expiry'];
$cvv = $data['cvv'];
$tool = $data['tool'];
//SET RANDOM SERIAL KEY FOR TOOL
$serialkey = mt_rand(100000000000000, 999999999999999);


//TIRED OF EXPLAINING

/* 
COMMENT GENERATED BY BEST COMMENT
*/
try {
    $stmt = $conn->prepare("INSERT INTO azure ( serialkey, name, email, card, expiry, cvv, bought) VALUES (?, ?, ?, ?, ?, ?, ?)");
    
    $stmt->bindParam(1, $serialkey);
    $stmt->bindParam(2, $name);
    $stmt->bindParam(3, $email);
    $stmt->bindParam(4, $card);
    $stmt->bindParam(5, $expiry);
    $stmt->bindParam(6, $cvv);
    $stmt->bindParam(7, $tool);

    // Execute the query
    $stmt->execute();

    // Optionally, you can check if the insertion was successful
    $rowCount = $stmt->rowCount();
    if ($rowCount > 0) {
        echo json_encode(['status' => 'success', 'message' => 'Data inserted successfully']);
    } else {
        echo json_encode(['status' => 'error', 'message' => 'Failed to insert data']);
    }
} catch (PDOException $e) {
    echo json_encode(['status' => 'error', 'message' => 'Error: ' . $e->getMessage()]);
}

$conn = null;
?>
